config/routes.rb
Lebensdauer::Application.routes.draw do
  resources :drugs

  resources :hospitals

  resources :visits

  resources :diseases

  resources :departments

  resources :medical_records

  resources :enterprises

  resources :vitals

  resources :equipment

  resources :facilities

  devise_for :users

  root :to => 'home#index'

end

app/models/blood_group.rb
class BloodGroup < ActiveRecord::Base
  attr_accessible :name
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :category
  belongs_to :dtype
  attr_accessible :affiliation
end

app/models/designation.rb
class Designation < ActiveRecord::Base
  attr_accessible :name
end

app/models/disease.rb
class Disease < ActiveRecord::Base
  attr_accessible :causes, :name, :symptoms
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  belongs_to :category
  attr_accessible :name, :price, :schedule
end

app/models/drug_category.rb
class DrugCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
  belongs_to :category
  attr_accessible :email, :fax, :name, :registration
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :cost, :name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :ftype, :class_name => 'FacilityType'
  belongs_to :location
  attr_accessible :close, :name, :open, :registration
end

app/models/facility_type.rb
class FacilityType < ActiveRecord::Base
  attr_accessible :name
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  belongs_to :location
  attr_accessible :availability, :capacity, :name
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :language
  belongs_to :marital_status
  belongs_to :nationality
  belongs_to :ethnicity
  attr_accessible :SSN, :address, :birthdate, :firstname, :lastname, :middlename, :phone, :photo, :sex
  
  def Sex
    sex == true ? 'Male' : 'Female'
  end
  
  def fullname
    "%s %s" % [firstname, lastname]
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :consultant
  belongs_to :vital
  attr_accessible :date, :issues, :prescriptions, :sensitivity
end

app/models/vital.rb
class Vital < ActiveRecord::Base
  attr_accessible :height, :pressure, :sugar, :weight
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  # GET /drugs
  # GET /drugs.json
  def index
    @drugs = Drug.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drugs }
    end
  end

  # GET /drugs/1
  # GET /drugs/1.json
  def show
    @drug = Drug.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drug }
    end
  end

  # GET /drugs/new
  # GET /drugs/new.json
  def new
    @drug = Drug.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drug }
    end
  end

  # GET /drugs/1/edit
  def edit
    @drug = Drug.find(params[:id])
  end

  # POST /drugs
  # POST /drugs.json
  def create
    @drug = Drug.new(params[:drug])

    respond_to do |format|
      if @drug.save
        format.html { redirect_to @drug, notice: 'Drug was successfully created.' }
        format.json { render json: @drug, status: :created, location: @drug }
      else
        format.html { render action: "new" }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drugs/1
  # PUT /drugs/1.json
  def update
    @drug = Drug.find(params[:id])

    respond_to do |format|
      if @drug.update_attributes(params[:drug])
        format.html { redirect_to @drug, notice: 'Drug was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1
  # DELETE /drugs/1.json
  def destroy
    @drug = Drug.find(params[:id])
    @drug.destroy

    respond_to do |format|
      format.html { redirect_to drugs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/drugs/_form.html.erb
<%= form_for(@drug) do |f| %>
  <% if @drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
      <% @drug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :schedule %><br />
    <%= f.text_field :schedule %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<h1>Editing drug</h1>

<%= render 'form' %>

<%= link_to 'Show', @drug %> |
<%= link_to 'Back', drugs_path %>

app/views/drugs/index.html.erb
<h1>Listing drugs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Schedule</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drugs.each do |drug| %>
  <tr>
    <td><%= drug.name %></td>
    <td><%= drug.category %></td>
    <td><%= drug.schedule %></td>
    <td><%= drug.price %></td>
    <td><%= link_to 'Show', drug %></td>
    <td><%= link_to 'Edit', edit_drug_path(drug) %></td>
    <td><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drug', new_drug_path %>

app/views/drugs/new.html.erb
<h1>New drug</h1>

<%= render 'form' %>

<%= link_to 'Back', drugs_path %>

app/views/drugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @drug.name %>
</p>

<p>
  <b>Category:</b>
  <%= @drug.category %>
</p>

<p>
  <b>Schedule:</b>
  <%= @drug.schedule %>
</p>

<p>
  <b>Price:</b>
  <%= @drug.price %>
</p>


<%= link_to 'Edit', edit_drug_path(@drug) %> |
<%= link_to 'Back', drugs_path %>