config/routes.rb
Lebensdauer::Application.routes.draw do
  resources :drugs

  resources :hospitals

  resources :visits

  resources :diseases

  resources :departments

  resources :medical_records

  resources :enterprises

  resources :vitals

  resources :equipment

  resources :facilities

  devise_for :users

  root :to => 'home#index'

end

app/models/blood_group.rb
class BloodGroup < ActiveRecord::Base
  attr_accessible :name
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :category
  belongs_to :dtype
  attr_accessible :affiliation
end

app/models/designation.rb
class Designation < ActiveRecord::Base
  attr_accessible :name
end

app/models/disease.rb
class Disease < ActiveRecord::Base
  attr_accessible :causes, :name, :symptoms
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  belongs_to :category
  attr_accessible :name, :price, :schedule
end

app/models/drug_category.rb
class DrugCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
  belongs_to :category
  attr_accessible :email, :fax, :name, :registration
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :cost, :name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :ftype, :class_name => 'FacilityType'
  belongs_to :location
  attr_accessible :close, :name, :open, :registration
end

app/models/facility_type.rb
class FacilityType < ActiveRecord::Base
  attr_accessible :name
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  belongs_to :location
  attr_accessible :availability, :capacity, :name
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :language
  belongs_to :marital_status
  belongs_to :nationality
  belongs_to :ethnicity
  attr_accessible :SSN, :address, :birthdate, :firstname, :lastname, :middlename, :phone, :photo, :sex
  
  def Sex
    sex == true ? 'Male' : 'Female'
  end
  
  def fullname
    "%s %s" % [firstname, lastname]
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :consultant
  belongs_to :vital
  attr_accessible :date, :issues, :prescriptions, :sensitivity
end

app/models/vital.rb
class Vital < ActiveRecord::Base
  attr_accessible :height, :pressure, :sugar, :weight
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :hospital %><br />
    <%= f.text_field :hospital %>
  </div>
  <div class="field">
    <%= f.label :consultant %><br />
    <%= f.text_field :consultant %>
  </div>
  <div class="field">
    <%= f.label :issues %><br />
    <%= f.text_field :issues %>
  </div>
  <div class="field">
    <%= f.label :prescriptions %><br />
    <%= f.text_area :prescriptions %>
  </div>
  <div class="field">
    <%= f.label :vital %><br />
    <%= f.text_field :vital %>
  </div>
  <div class="field">
    <%= f.label :sensitivity %><br />
    <%= f.text_field :sensitivity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Hospital</th>
    <th>Consultant</th>
    <th>Issues</th>
    <th>Prescriptions</th>
    <th>Vital</th>
    <th>Sensitivity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.date %></td>
    <td><%= visit.hospital %></td>
    <td><%= visit.consultant %></td>
    <td><%= visit.issues %></td>
    <td><%= visit.prescriptions %></td>
    <td><%= visit.vital %></td>
    <td><%= visit.sensitivity %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @visit.date %>
</p>

<p>
  <b>Hospital:</b>
  <%= @visit.hospital %>
</p>

<p>
  <b>Consultant:</b>
  <%= @visit.consultant %>
</p>

<p>
  <b>Issues:</b>
  <%= @visit.issues %>
</p>

<p>
  <b>Prescriptions:</b>
  <%= @visit.prescriptions %>
</p>

<p>
  <b>Vital:</b>
  <%= @visit.vital %>
</p>

<p>
  <b>Sensitivity:</b>
  <%= @visit.sensitivity %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>