config/routes.rb
Lebensdauer::Application.routes.draw do
  resources :drugs

  resources :hospitals

  resources :visits

  resources :diseases

  resources :departments

  resources :medical_records

  resources :enterprises

  resources :vitals

  resources :equipment

  resources :facilities

  devise_for :users

  root :to => 'home#index'

end

app/models/blood_group.rb
class BloodGroup < ActiveRecord::Base
  attr_accessible :name
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :category
  belongs_to :dtype
  attr_accessible :affiliation
end

app/models/designation.rb
class Designation < ActiveRecord::Base
  attr_accessible :name
end

app/models/disease.rb
class Disease < ActiveRecord::Base
  attr_accessible :causes, :name, :symptoms
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  belongs_to :category
  attr_accessible :name, :price, :schedule
end

app/models/drug_category.rb
class DrugCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
  belongs_to :category
  attr_accessible :email, :fax, :name, :registration
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :cost, :name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :ftype, :class_name => 'FacilityType'
  belongs_to :location
  attr_accessible :close, :name, :open, :registration
end

app/models/facility_type.rb
class FacilityType < ActiveRecord::Base
  attr_accessible :name
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  belongs_to :location
  attr_accessible :availability, :capacity, :name
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
end

app/models/medical_record.rb
class MedicalRecord < ActiveRecord::Base
  attr_accessible :closure, :comments, :onset
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :language
  belongs_to :marital_status
  belongs_to :nationality
  belongs_to :ethnicity
  attr_accessible :SSN, :address, :birthdate, :firstname, :lastname, :middlename, :phone, :photo, :sex
  
  def Sex
    sex == true ? 'Male' : 'Female'
  end
  
  def fullname
    "%s %s" % [firstname, lastname]
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :consultant
  belongs_to :vital
  attr_accessible :date, :issues, :prescriptions, :sensitivity
end

app/models/vital.rb
class Vital < ActiveRecord::Base
  attr_accessible :height, :pressure, :sugar, :weight
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  # GET /medical_records
  # GET /medical_records.json
  def index
    @medical_records = MedicalRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medical_records }
    end
  end

  # GET /medical_records/1
  # GET /medical_records/1.json
  def show
    @medical_record = MedicalRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medical_record }
    end
  end

  # GET /medical_records/new
  # GET /medical_records/new.json
  def new
    @medical_record = MedicalRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medical_record }
    end
  end

  # GET /medical_records/1/edit
  def edit
    @medical_record = MedicalRecord.find(params[:id])
  end

  # POST /medical_records
  # POST /medical_records.json
  def create
    @medical_record = MedicalRecord.new(params[:medical_record])

    respond_to do |format|
      if @medical_record.save
        format.html { redirect_to @medical_record, notice: 'Medical record was successfully created.' }
        format.json { render json: @medical_record, status: :created, location: @medical_record }
      else
        format.html { render action: "new" }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medical_records/1
  # PUT /medical_records/1.json
  def update
    @medical_record = MedicalRecord.find(params[:id])

    respond_to do |format|
      if @medical_record.update_attributes(params[:medical_record])
        format.html { redirect_to @medical_record, notice: 'Medical record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1
  # DELETE /medical_records/1.json
  def destroy
    @medical_record = MedicalRecord.find(params[:id])
    @medical_record.destroy

    respond_to do |format|
      format.html { redirect_to medical_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/views/medical_records/_form.html.erb
<%= form_for(@medical_record) do |f| %>
  <% if @medical_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
      <% @medical_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :onset %><br />
    <%= f.date_select :onset %>
  </div>
  <div class="field">
    <%= f.label :closure %><br />
    <%= f.date_select :closure %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medical_records/edit.html.erb
<h1>Editing medical_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @medical_record %> |
<%= link_to 'Back', medical_records_path %>

app/views/medical_records/index.html.erb
<h1>Listing medical_records</h1>

<table>
  <tr>
    <th>Onset</th>
    <th>Closure</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medical_records.each do |medical_record| %>
  <tr>
    <td><%= medical_record.onset %></td>
    <td><%= medical_record.closure %></td>
    <td><%= medical_record.comments %></td>
    <td><%= link_to 'Show', medical_record %></td>
    <td><%= link_to 'Edit', edit_medical_record_path(medical_record) %></td>
    <td><%= link_to 'Destroy', medical_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medical record', new_medical_record_path %>

app/views/medical_records/new.html.erb
<h1>New medical_record</h1>

<%= render 'form' %>

<%= link_to 'Back', medical_records_path %>

app/views/medical_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Onset:</b>
  <%= @medical_record.onset %>
</p>

<p>
  <b>Closure:</b>
  <%= @medical_record.closure %>
</p>

<p>
  <b>Comments:</b>
  <%= @medical_record.comments %>
</p>


<%= link_to 'Edit', edit_medical_record_path(@medical_record) %> |
<%= link_to 'Back', medical_records_path %>