config/routes.rb
Lebensdauer::Application.routes.draw do
  resources :drugs

  resources :hospitals

  resources :visits

  resources :diseases

  resources :departments

  resources :medical_records

  resources :enterprises

  resources :vitals

  resources :equipment

  resources :facilities

  devise_for :users

  root :to => 'home#index'

end

app/models/blood_group.rb
class BloodGroup < ActiveRecord::Base
  attr_accessible :name
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :category
  belongs_to :dtype
  attr_accessible :affiliation
end

app/models/designation.rb
class Designation < ActiveRecord::Base
  attr_accessible :name
end

app/models/disease.rb
class Disease < ActiveRecord::Base
  attr_accessible :causes, :name, :symptoms
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  belongs_to :category
  attr_accessible :name, :price, :schedule
end

app/models/drug_category.rb
class DrugCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
  belongs_to :category
  attr_accessible :email, :fax, :name, :registration
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :cost, :name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  belongs_to :ftype, :class_name => 'FacilityType'
  belongs_to :location
  attr_accessible :close, :name, :open, :registration
end

app/models/facility_type.rb
class FacilityType < ActiveRecord::Base
  attr_accessible :name
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  belongs_to :location
  attr_accessible :availability, :capacity, :name
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
  attr_accessible :name
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :language
  belongs_to :marital_status
  belongs_to :nationality
  belongs_to :ethnicity
  attr_accessible :SSN, :address, :birthdate, :firstname, :lastname, :middlename, :phone, :photo, :sex
  
  def Sex
    sex == true ? 'Male' : 'Female'
  end
  
  def fullname
    "%s %s" % [firstname, lastname]
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :consultant
  belongs_to :vital
  attr_accessible :date, :issues, :prescriptions, :sensitivity
end

app/models/vital.rb
class Vital < ActiveRecord::Base
  attr_accessible :height, :pressure, :sugar, :weight
end

app/controllers/vitals_controller.rb
class VitalsController < ApplicationController
  # GET /vitals
  # GET /vitals.json
  def index
    @vitals = Vital.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vitals }
    end
  end

  # GET /vitals/1
  # GET /vitals/1.json
  def show
    @vital = Vital.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vital }
    end
  end

  # GET /vitals/new
  # GET /vitals/new.json
  def new
    @vital = Vital.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vital }
    end
  end

  # GET /vitals/1/edit
  def edit
    @vital = Vital.find(params[:id])
  end

  # POST /vitals
  # POST /vitals.json
  def create
    @vital = Vital.new(params[:vital])

    respond_to do |format|
      if @vital.save
        format.html { redirect_to @vital, notice: 'Vital was successfully created.' }
        format.json { render json: @vital, status: :created, location: @vital }
      else
        format.html { render action: "new" }
        format.json { render json: @vital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vitals/1
  # PUT /vitals/1.json
  def update
    @vital = Vital.find(params[:id])

    respond_to do |format|
      if @vital.update_attributes(params[:vital])
        format.html { redirect_to @vital, notice: 'Vital was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vitals/1
  # DELETE /vitals/1.json
  def destroy
    @vital = Vital.find(params[:id])
    @vital.destroy

    respond_to do |format|
      format.html { redirect_to vitals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/vitals/_form.html.erb
<%= form_for(@vital) do |f| %>
  <% if @vital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vital.errors.count, "error") %> prohibited this vital from being saved:</h2>

      <ul>
      <% @vital.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :pressure %><br />
    <%= f.text_field :pressure %>
  </div>
  <div class="field">
    <%= f.label :sugar %><br />
    <%= f.text_field :sugar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vitals/edit.html.erb
<h1>Editing vital</h1>

<%= render 'form' %>

<%= link_to 'Show', @vital %> |
<%= link_to 'Back', vitals_path %>

app/views/vitals/index.html.erb
<h1>Listing vitals</h1>

<table>
  <tr>
    <th>Weight</th>
    <th>Height</th>
    <th>Pressure</th>
    <th>Sugar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vitals.each do |vital| %>
  <tr>
    <td><%= vital.weight %></td>
    <td><%= vital.height %></td>
    <td><%= vital.pressure %></td>
    <td><%= vital.sugar %></td>
    <td><%= link_to 'Show', vital %></td>
    <td><%= link_to 'Edit', edit_vital_path(vital) %></td>
    <td><%= link_to 'Destroy', vital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vital', new_vital_path %>

app/views/vitals/new.html.erb
<h1>New vital</h1>

<%= render 'form' %>

<%= link_to 'Back', vitals_path %>

app/views/vitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Weight:</b>
  <%= @vital.weight %>
</p>

<p>
  <b>Height:</b>
  <%= @vital.height %>
</p>

<p>
  <b>Pressure:</b>
  <%= @vital.pressure %>
</p>

<p>
  <b>Sugar:</b>
  <%= @vital.sugar %>
</p>


<%= link_to 'Edit', edit_vital_path(@vital) %> |
<%= link_to 'Back', vitals_path %>